### ISSUE TITLE
QA Rosbag 2 QoS: Override Scenarios

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/aws-roadmap#284]
## Description

Test the following [override](https://github.com/ros-tooling/aws-roadmap/issues/218) scenarios using rosbag2:

 - pass invalid overrides for playback and recording
 - pass valid overrides for recording
 - pass valid overrides for playback

The following configurations should be tested to ensure the feature works on all platforms and middlewares:

|  *Operating System* |
|-------------------|
|   OSX |
|  Windows |
|  Linux x86_64 |  

|  *RMW* |
|-------------------|
|   FastRTPS |
|  Connext |
|  CycloneDDS |  

**Priority**
 - Linux + default RMW, non default RMW
 - Windows + default RMW, non default RMW
 - OSX + default RMW, non default RMW

## Spike Timeboxing

1.5 days

## Spike Outcome

 * github tickets if any bugs are found
 * document (or comment update here) how to reproduce manual tests

**Comment by dabonnie** [comment]
Valid overrides were tested on all configurations via https://github.com/ros-tooling/aws-roadmap/issues/277#issuecomment-635547152 

To test invalid overrides:

Install the prerequisites and [fat binaries](https://index.ros.org/doc/ros2/Installation/Prerelease-Testing/) on the target platform. 

`rclcpp`
 -
'rclpy'
 - 

- Linux
  - FastRTPS
    - [ ] rclcpp
    - [ ] rclpy
  - RTI Connext
    - [ ] rclcpp
    - [ ] rclpy
  - Cyclone DDS
    - [ ] rclcpp
    - [ ] rclpy
- OSX
  - FastRTPS
    - [ ] rclcpp
    - [ ] rclpy
  - RTI Connext
    - [ ] rclcpp
    - [ ] rclpy
  - Cyclone DDS
    - [ ] rclcpp
    - [ ] rclpy
- Windows
  - FastRTPS
    - [ ] rclcpp
    - [ ] rclpy
  - RTI Connext
    - [ ] rclcpp
    - [ ] rclpy
  - Cyclone DDS
    - [ ] rclcpp
    - [ ] rclpy

**Comment by dabonnie** [comment]
Filed https://github.com/ros2/rosbag2/issues/431

**Comment by dabonnie** [comment]
manual_by_node is considered a bad input for liveliness, but the [wiki](https://index.ros.org/doc/ros2/Tutorials/Ros2bag/Overriding-QoS-Policies-For-Recording-And-Playback/) says otherwise.

```
/test:
  history: keep_all
  depth: 5
  liveliness: manual_by_node
  liveliness_lease_duration:
    sec: 5
    nsec: 6
  avoid_ros_namespace_conventions: true
```

```
ros2 bag play test/ --qos-profile-overrides-path bad_liveliness2.yaml 
Traceback (most recent call last):
  File "/Users/dbbonnie/fat_archive/ros2-osx/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.9.4', 'console_scripts', 'ros2')()
  File "/Users/dbbonnie/fat_archive/ros2-osx/lib/python3.8/site-packages/ros2cli/cli.py", line 67, in main
    rc = extension.main(parser=parser, args=args)
  File "/Users/dbbonnie/fat_archive/ros2-osx/lib/python3.8/site-packages/ros2bag/command/bag.py", line 38, in main
    return extension.main(args=args)
  File "/Users/dbbonnie/fat_archive/ros2-osx/lib/python3.8/site-packages/ros2bag/verb/play.py", line 65, in main
    qos_profile_overrides = convert_yaml_to_qos_profile(
  File "/Users/dbbonnie/fat_archive/ros2-osx/lib/python3.8/site-packages/ros2bag/api/__init__.py", line 74, in convert_yaml_to_qos_profile
    topic_profile_dict[topic] = interpret_dict_as_qos_profile(profile)
  File "/Users/dbbonnie/fat_archive/ros2-osx/lib/python3.8/site-packages/ros2bag/api/__init__.py", line 62, in interpret_dict_as_qos_profile
    new_profile_dict[policy_key] = _QOS_POLICY_FROM_SHORT_NAME[policy_key](policy_value)
  File "/Users/dbbonnie/fat_archive/ros2-osx/lib/python3.8/site-packages/rclpy/qos.py", line 287, in get_from_short_key
    return cls[name.upper()].value
  File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/enum.py", line 344, in __getitem__
    return cls._member_map_[name]
KeyError: 'MANUAL_BY_NODE'
```

```
ros2 bag record -a --qos-profile-overrides-path bad_liveliness2.yaml 
Traceback (most recent call last):
  File "/Users/dbbonnie/fat_archive/ros2-osx/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.9.4', 'console_scripts', 'ros2')()
  File "/Users/dbbonnie/fat_archive/ros2-osx/lib/python3.8/site-packages/ros2cli/cli.py", line 67, in main
    rc = extension.main(parser=parser, args=args)
  File "/Users/dbbonnie/fat_archive/ros2-osx/lib/python3.8/site-packages/ros2bag/command/bag.py", line 38, in main
    return extension.main(args=args)
  File "/Users/dbbonnie/fat_archive/ros2-osx/lib/python3.8/site-packages/ros2bag/verb/record.py", line 106, in main
    qos_profile_overrides = convert_yaml_to_qos_profile(
  File "/Users/dbbonnie/fat_archive/ros2-osx/lib/python3.8/site-packages/ros2bag/api/__init__.py", line 74, in convert_yaml_to_qos_profile
    topic_profile_dict[topic] = interpret_dict_as_qos_profile(profile)
  File "/Users/dbbonnie/fat_archive/ros2-osx/lib/python3.8/site-packages/ros2bag/api/__init__.py", line 62, in interpret_dict_as_qos_profile
    new_profile_dict[policy_key] = _QOS_POLICY_FROM_SHORT_NAME[policy_key](policy_value)
  File "/Users/dbbonnie/fat_archive/ros2-osx/lib/python3.8/site-packages/rclpy/qos.py", line 287, in get_from_short_key
    return cls[name.upper()].value
  File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/enum.py", line 344, in __getitem__
    return cls._member_map_[name]
KeyError: 'MANUAL_BY_NODE'
```
